parser: 'babel-eslint'

parserOptions:
  ecmaVersion: 2018
  sourceType: 'module'
  allowImportExportEverywhere: true

settings:
  react:
    version: 'detect'

env:
  es6: true
  browser: true
  commonjs: true
  jest: true
  node: true

rules:
  no-process-env: off
  quotes: ['warn', 'backtick']
  curly: 'error'
  no-lonely-if: 'error'
  no-console: 'error'

extends: ['eslint:recommended', 'plugin:react/recommended', 'plugin:prettier/recommended', 'plugin:json/recommended']
